name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { r: '4.0.5' }
          - { r: '4.1.0' }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libssl-dev libcurl4-openssl-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ~/.R/Library
        key: ${{ runner.os }}-R-${{ matrix.config.r }}-${{ hashFiles('DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-R-${{ matrix.config.r }}-

    - name: Install R package dependencies
      run: |
        install.packages(c('devtools', 'textshaping', 'ragg', 'pkgdown'), dependencies = TRUE)
        devtools::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Run R CMD check
      run: |
        library(devtools)
        check()
      shell: Rscript {0}

    - name: Upload check results
      if: always() # Ensure logs are uploaded even if the step fails
      uses: actions/upload-artifact@v2
      with:
        name: R-CMD-check-results
        path: check

    - name: Save R-CMD-check logs
      if: always() # Ensure logs are uploaded even if the step fails
      uses: actions/upload-artifact@v2
      with:
        name: R-CMD-check-logs
        path: check
